### ISSUE TITLE
require auth setting for apps

### ISSUE THREAD

**Issue by asida18** [RIAEvangelist/awesome-webcomponents#28]
Can you extend this login screen component to:
           **include possible property of 'data-requireAuth' which can be set as either 'true' or 'false'**
           **navigation to screen/page after successful login/authentication**

**Comment by RIAEvangelist** [comment]
I don't think this should be based on the login screen, I think it should be based on the app or body somehow.

**Comment by asida18** [comment]
@RIAEvangelist touché.

**Comment by RIAEvangelist** [comment]
released with bb7b57b v0.0.65
