### ISSUE TITLE
Clear screen state on logout success 

### ISSUE THREAD

**Issue by MaybeRex** [RIAEvangelist/awesome-webcomponents#35]
# Clear screen state on logout success

Clear the states on logout so it does not navigate to previous screen on login

**Comment by RIAEvangelist** [comment]
I do not think this is ideal for all scenarios.

There will be scenarios when a timeout logs the user out, or locks their app. In these scenarios a user would want to be directed back to where they came from.

This should be handled elsewhere or in a different action for an app which also listens for the logout action.

But, it should be explicit behavior not implicit.
