### ISSUE TITLE
Awesome-login-screen data action path not preventing standard auth from loading.

### ISSUE THREAD

**Issue by MaybeRex** [RIAEvangelist/awesome-webcomponents#37]
# awesome-login-screen

awesome-login-sceen data-action path should accept a template string as a path

**Comment by RIAEvangelist** [comment]
you need to make better titles.

**Comment by RIAEvangelist** [comment]
also, your bug report states what it should be doing. so its not reporting anything.

**Comment by RIAEvangelist** [comment]
should read similar to the following :

if awesome-login-sceen data-action path is specified it should prevent the default auth from loading, but both are still loading.

**Comment by RIAEvangelist** [comment]
reporting bugs clearly is a very important skill if you want them to be fixed. ;)

**Comment by asida18** [comment]
To load one's own action for use in awesome-login-screen within a html screen or index, we must currently do as so within the script tags:

const login=document.createElement('awesome-login-screen');
            login.dataset.action_path=`${proprietaryrepo.path}actions/yourAuth.js`;
            window.on(
                'DOMContentLoaded',
                function(){
                    document.body.appendChild(login);
                }
            )

Please change to solution shown below :

const login=document.createElement('awesome-login-screen');
            login.dataset.action_path=`${proprietaryrepo.path}actions/yourAuth.js`;
            awesome.appendComponent(login);

**Comment by RIAEvangelist** [comment]
plz make new issue @asida18
